Fixed cuvs benchmark debug build issue (linker step fail) (#1599)
Building cuVS benchmarks in Debug mode would fail during linker step with the following (e.g.) message
`[ 97%] Built target cuvs_c
/usr/bin/ld: ../../libcuvs.so: undefined reference to `cuvs::neighbors::hnsw::index<unsigned char>::set_ef(int) const'
/usr/bin/ld: ../../libcuvs.so: undefined reference to `cuvs::neighbors::hnsw::index<__half>::set_ef(int) const'
/usr/bin/ld: ../../libcuvs.so: undefined reference to `cuvs::neighbors::hnsw::index<float>::set_ef(int) const'
/usr/bin/ld: ../../libcuvs.so: undefined reference to `cuvs::neighbors::hnsw::index<signed char>::set_ef(int) const'`
An example CMake command:
`cmake .. -DCUVS_NVTX=ON -DBUILD_MG_ALGOS=OFF -DBUILD_TESTS=OFF -DBUILD_C_TESTS=OFF -DBUILD_CUVS_BENCH=ON -DCUVS_ANN_BENCH_USE_FAISS_GPU_FLAT=OFF -DCUVS_ANN_BENCH_USE_FAISS_GPU_IVF_FLAT=OFF -DCUVS_ANN_BENCH_USE_FAISS_GPU_CAGRA=OFF -DCUVS_ANN_BENCH_USE_FAISS_GPU_IVF_PQ=OFF -DCUVS_ANN_BENCH_USE_FAISS_CPU_FLAT=OFF -DCUVS_ANN_BENCH_USE_FAISS_CPU_IVF_FLAT=OFF -DCUVS_ANN_BENCH_USE_FAISS_CPU_IVF_PQ=OFF -DCUVS_ANN_BENCH_USE_FAISS_CPU_HNSW_FLAT=OFF -DCUVS_ANN_BENCH_USE_FAISS_GPU_CAGRA_HNSW=OFF -DCUVS_ANN_BENCH_USE_CUVS_CAGRA_HNSWLIB=OFF -DCUVS_ANN_BENCH_USE_HNSWLIB=OFF -DCUVS_ANN_BENCH_USE_GGNN=OFF -DCUVS_ANN_BENCH_USE_DISKANN=OFF -DCUVS_ANN_BENCH_USE_CUVS_VAMANA=OFF -DCUVS_ANN_BENCH_USE_CUVS_CAGRA_DISKANN=OFF -DCUVS_ANN_BENCH_USE_CUVS_MG=OFF -DDISABLE_DEPRECATION_WARNINGS=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_CUDA_ARCHITECTURES=80 -DCMAKE_BUILD_TYPE=Debug`

The same code would still compile in Release mode (probably due to compile optimisation)

The fix just declares 
cuvs::neighbors::hnsw::index::set_ef(int) function as purely virtual.

Authors:
  - https://github.com/irina-resh-nvda
  - Corey J. Nolet (https://github.com/cjnolet)
  - Tamas Bela Feher (https://github.com/tfeher)

Approvers:
  - Malte Förster (https://github.com/mfoerste4)
  - Divye Gala (https://github.com/divyegala)
  - Corey J. Nolet (https://github.com/cjnolet)

URL: https://github.com/rapidsai/cuvs/pull/1599