Fix a bug in compute_distance_00_generate.py (#1532)
This PR fixes the following error:
```
python compute_distance_00_generate.py
Traceback (most recent call last):
  File "/.../cuvs/cpp/src/neighbors/detail/cagra/compute_distance_00_generate.py", line 21, in <module>
    {includes}
     ^^^^^^^^
NameError: name 'includes' is not defined
```
The error occurs because `{includes}` is unintentionally interpreted as a format field when `{datetime.datetime.today().year}`  is processed.

Authors:
  - tsuki (https://github.com/enp1s0)

Approvers:
  - Artem M. Chirkin (https://github.com/achirkin)

URL: https://github.com/rapidsai/cuvs/pull/1532